version: "3.9"
services:
  sqlserver-identity:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-identity
    ports:
      - "1434:1433"  # 🔹 Each database has a unique exposed port
    environment:
      SA_PASSWORD: "MarioKondPassword123"
      ACCEPT_EULA: "Y"
      MSSQL_TCP_PORT: 1433
    networks:
      - socialnetwork

  sqlserver-people:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-people
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "MarioKondPassword123"
      ACCEPT_EULA: "Y"
      MSSQL_TCP_PORT: 1433
    networks:
      - socialnetwork

  sqlserver-posts:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-posts
    ports:
      - "1436:1433"
    environment:
      SA_PASSWORD: "MarioKondPassword123"
      ACCEPT_EULA: "Y"
      MSSQL_TCP_PORT: 1433
    networks:
      - socialnetwork

  identity-api:
    build:
      context: ./IdentityAPI
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver-identity,1433;Database=IdentityDB;User=sa;Password=MarioKondPassword123;TrustServerCertificate=True;Encrypt=False
      - JwtSettings__Secret=SuperSecretKey123456789JWTSuperSekretnyKlucz
      - JwtSettings__Issuer=IdentityAPI
      - JwtSettings__Audience=SocialBook
    depends_on:
      - sqlserver-identity
    networks:
      - socialnetwork

  people-api:
    build:
      context: ./PeopleAPI
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver-people,1433;Database=PeopleDB;User=sa;Password=MarioKondPassword123;TrustServerCertificate=True;Encrypt=False
    depends_on:
      - sqlserver-people
    networks:
      - socialnetwork

  post-api:
    build:
      context: ./PostAPI
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver-posts,1433;Database=PostDB;User=sa;Password=MarioKondPassword123;TrustServerCertificate=True;Encrypt=False
    depends_on:
      - sqlserver-posts
    networks:
      - socialnetwork

networks:
  socialnetwork:
    driver: bridge
