services:
  sqlserver-identity:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-identity
    expose:
      - "1433"
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "MarioKondPassword123"
      ACCEPT_EULA: "Y"
    networks:
      - socialnetwork

  sqlserver-people:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-people
    expose:
      - "1433"
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "MarioKondPassword123"
      ACCEPT_EULA: "Y"
    networks:
      - socialnetwork

  sqlserver-posts:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-posts
    expose:
      - "1433"
    ports:
      - "1436:1433"
    environment:
      SA_PASSWORD: "MarioKondPassword123"
      ACCEPT_EULA: "Y"
    networks:
      - socialnetwork

  identity-api:
    build:
      dockerfile: IdentityAPI/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver-identity;Database=IdentityDB;User=sa;Password=MarioKondPassword123;TrustServerCertificate=True;Encrypt=False;
      - JwtSettings__Secret=SuperSecretKey123456789JWTSuperSekretnyKlucz
      - JwtSettings__Issuer=IdentityAPI
      - JwtSettings__Audience=SocialBook
    depends_on:
      - sqlserver-identity
    networks:
      - socialnetwork

  people-api:
    build:
      dockerfile: PeopleAPI/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver-people;Database=PeopleDB;User=sa;Password=MarioKondPassword123;TrustServerCertificate=True;Encrypt=False;
    depends_on:
      - sqlserver-people
    networks:
      - socialnetwork

  post-api:
    build:
      dockerfile: PostAPI/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver-posts;Database=PostDB;User=sa;Password=MarioKondPassword123;TrustServerCertificate=True;Encrypt=False;
    depends_on:
      - sqlserver-posts
    networks:
      - socialnetwork

networks:
  socialnetwork:
    driver: bridge
